DROP DATABASE IF EXISTS basicCardDB;
CREATE DATABASE basicCardDB;

USE basicCardDB;

CREATE TABLE cards(
	id INT NOT NULL AUTO_INCREMENT,
	front VARCHAR(500) NOT NULL,
	back VARCHAR(500) NOT NULL,
	PRIMARY KEY (id)
);